# docker-compose.yml
services:
  erp-agent:
    build: .
    container_name: erp-agent
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
